#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yuta Sekino
# SPDX-License-Identifier: BSD-3-Clause
import sys

plus_ans = 0
minus_ans = 0

for line in sys.stdin:
   try:
      num1 = int(line)
      plus_ans += num1
      minus_ans -= num1
   except:
      num2 = float(line)
      plus_ans += num2
      minus_ans -= num2 

print(f"{plus_ans},{minus_ans}")
